import { Utils } from "./Utils";

const arrNamePlayer = [
    "Aaron Friedman",
    "Abdallah M Hillu",
    "Alec Richker",
    "Alex Rudinger",
    "Alexander Saavedra",
    "Alexis Kanarek",
    "Alyssa Cavallaro",
    "Amanda Coates Lich",
    "Amanda Hayden Powell",
    "Amanda Seidel",
    "Amie Wade",
    "Amit Kaul",
    "Amy Minyard",
    "Amy Morris Goody",
    "Amy Williams Luttrell",
    "An Phan",
    "Andrew Golden",
    "Andrew Holder",
    "Angel Andre Kent",
    "Angelo Ricasa",
    "Angie Grant",
    "Antonio Misuraca",
    "Arielle Ehrlich",
    "Arkady Farberov",
    "Bailey Handzel",
    "Bao Ngoc Vu",
    "Barbara Amos Revlett",
    "Bashar Daoud",
    "Becca Sass",
    "Benjamin Nissen",
    "Benjamin Savard",
    "Beth Clark",
    "Beth Clark",
    "Bethani Blume",
    "Bethany Mclean",
    "Bill Connolly",
    "Bill Dean",
    "Blue Arauz",
    "Bogdan Cristian",
    "Bong Bing",
    "Bradley Ingram",
    "Brandi Leigh",
    "Brandon Gell",
    "Brandy Lynn Burkeen",
    "Brennan Dennis",
    "Brett David",
    "Brian Almond",
    "Brian Frazee",
    "Brian Mayers",
    "Brianna Steed",
    "Brooke Renfrow",
    "Bryan Sysko",
    "Caitlyn Reading",
    "Caleb Smith",
    "Camila Santana",
    "Camila Santana",
    "Cara Dore",
    "Carissa Rea",
    "Carla Allen Statton",
    "Carlos Gato",
    "Carlos Pachas",
    "Carmel Sheppard Rich",
    "Carrie Elizabeth Cook",
    "Cathy Cowan Johnson",
    "Celia Marie",
    "Chandara Vanna.png",
    "Cheyenne Rosser",
    "Chloe Crager",
    "Chris Gale",
    "Chris Tingley",
    "Chuck Cohen",
    "Cindy Suiter",
    "Clark Robinson",
    "Crystal Ann",
    "Cyndi Anderson Jones",
    "Cyntha Atkinson",
    "Cynthia Schmautz",
    "Daisy J. Voytenkov",
    "Daniel Green",
    "Daniel Spencer",
    "Daniel Teixeira",
    "Danielle West",
    "Danniyal Ahmed",
    "Dario Natarelli",
    "Dave Edmonds",
    "David Chung",
    "David Dawson",
    "David Dawson",
    "David Friedman",
    "David Smith",
    "David Smith",
    "Dennis J Fawk",
    "Dhilu Amna",
    "Diana Giraldo",
    "Doan Pham Quoc",
    "Drew Lockyer",
    "Duke Raoum",
    "Duong Pham Duong",
    "Dyna NooNa",
    "Edward Gonzalez",
    "Edward Waseleski",
    "Elizabeth Morgan Johnson",
    "Emily Keeton Hopper",
    "Eric Zeitlin",
    "Erich Dylus",
    "Erika Potts",
    "Evan Glover",
    "Francisco Feliciano",
    "Gia Le",
    "Gia Lệ",
    "Gia Le",
    "Gilbert Benhamou",
    "Graham Hancock",
    "Greg Myers",
    "Hafi Hafa",
    "Haleigh Harris",
    "Hang Ruby",
    "Hanh Phan",
    "Hannah Griffin",
    "Henri Lauriel Wolfshoen",
    "Hilda Downen",
    "Hope Bowman",
    "Immanuel Alonza",
    "Ivy Diel",
    "J.A. de Medeiros",
    "Jack Harmon",
    "Jakob Reinhardt",
    "James Scarola",
    "Jamie Thomason-Allen",
    "Janae Fecondo",
    "Janie Pittman McDonald",
    "Jason Palumbo",
    "JayRich",
    "Jeffrey Jones",
    "Jen Bergeron",
    "Jenifer Naomi",
    "Jenny M. Legg",
    "Jeremy Wallace",
    "Jesse Bendit",
    "Joan Howard",
    "Jodi Casazza",
    "John Alexiades",
    "John Arash Habibi",
    "John August",
    "John Cephas",
    "John Lockwood",
    "Jonathan Lim",
    "Jordon Cunningham",
    "Josette Serrano",
    "Josh Russakis",
    "Joshua Robusto",
    "Julee Burt",
    "Julio Iguina-Pascual",
    "Kay Sanders",
    "Kelly Shillaber",
    "Kevin Feeney",
    "Kevin John Murray",
    "Kiarra Goldberg",
    "Kim Griffin De-Nise",
    "Kim Phap",
    "Kimberly Smith McPherson",
    "Klara Farberov",
    "Krystal Riehle",
    "Kyle Beneski",
    "Kylee Mitchell",
    "Kyli Christenson",
    "Lam Tuyet Nhung",
    "Laura K Harper",
    "Lauren Echausse",
    "Lauren Obeng",
    "Laurence K Aikens",
    "Len Da",
    "Len Jones",
    "Lena Tarrants",
    "Leo Ash Evens",
    "Lindsey Himmel",
    "Lisa Harris",
    "Liz Bur",
    "Logan Gonzalez",
    "Lola Beckman",
    "Luke McGinnis",
    "Maeve Berry",
    "Mandy Abney",
    "Marc Tumminelli",
    "Mark Aldrich",
    "Mary Oerther",
    "Mary Sparr",
    "Marygrace Tabelisma",
    "Matthew A. Schneider",
    "Matthew Jones",
    "Matthew Jones",
    "Matthew Levine",
    "Mckenzie Mattingly",
    "Megan Moschell",
    "Mert Karagoz",
    "Mia Lane Dreyfuss",
    "Mia NaKya Bethea",
    "Michael Bild",
    "Michael Hopewell",
    "Michael Longoria",
    "Michelle Haycraft",
    "Mike Hannon",
    "Mike Jones",
    "Mike Streltsov",
    "Mitchell Lombard",
    "Morgan Atkinson",
    "Myelz Ocadiz",
    "Nadav Benimetzky",
    "Nadia Hornung",
    "Nancy Jane",
    "Natalie Shea Sharp",
    "Nathan Rehr",
    "Nathaniel Vitan",
    "Nguyen Bao Toan",
    "Nguyen Thuy Hang",
    "Nick Laughlin",
    "Nick Nilson",
    "Odera Adigwe",
    "Patrick Kinley",
    "Patrick Taebok Lee",
    "Paul Luck",
    "Phan Bich Loan",
    "Phillip Cooper",
    "Rachel Joyce",
    "Rachel Leigh",
    "Ramiro Paez",
    "Rebekah Nash",
    "Rich Dixon",
    "Richard Alexander Bellofatto",
    "Richard C. Allin Jr.",
    "Richard Fawk",
    "Rob Crosoli",
    "Rob Frndz",
    "Robin Gregory",
    "Rodney Terry",
    "Russ Chandler",
    "Sarah Anna",
    "Sarann Chea",
    "Scott Parker",
    "Sean Ryan Paris",
    "Sebas Agudelo",
    "Sebastian Funk",
    "Sergey Feldman",
    "Shannon Moore",
    "Shari Kaufman Pordes",
    "Shawna Nally",
    "Sheila Gregory",
    "Sherry Thompson",
    "Sofia Charvet",
    "Sonia Gibson",
    "Spencer Brennen",
    "Spencer Prime",
    "Stacy Lovell Potts",
    "Starr Gremillion",
    "Stephanie A Cowan",
    "Sue Fields",
    "Suhail Sikka",
    "Sunggyun Kim",
    "Susan Dadaian",
    "Susan McPhaill Brown",
    "Susan Rolfe",
    "Susan Sawyer-Foster",
    "Suveena Ajmal",
    "Talazia Boards",
    "Tammy McGehee",
    "Tang Mong Kha",
    "Tara Winston",
    "Taylor Oates",
    "Ted Sullivan",
    "Teddy Gold",
    "Terri Ann Chaney-Cox",
    "Tiffany Bricker",
    "Tinh Van Ha",
    "TJ Tolson",
    "Tonya Davenport",
    "Tre Ok",
    "Trey Gerrald",
    "Trih Bubu",
    "Truong Thi Kim Huong",
    "Ty Kunzelman",
    "Uri Bokk",
    "Victor Pham",
    "Vishal Dwivedi",
    "Vy MiNi",
    "Wes Drummond",
    "Whitney House",
    "William Danielle Prince",
    "William Guille Klotz",
    "Youri Marien",
    "Zach Antell",
    "Zain Bamji",
]
export default class NameBot{
    static getArrName(){
        let arrName = arrNamePlayer.concat();
        Utils.shuffle(arrName);
        return arrName;
    }
}